### ISSUE TITLE
LFS Quota Issue Cloning Project (within unity and manually)

### ISSUE THREAD

**Issue by ghost** [Unity-Technologies/com.unity.cloud.gltfast#15]
**Describe the bug**

When cloning, I see:
```
> git clone https://github.com/Unity-Technologies/com.unity.cloud.gltfast.git
Cloning into 'com.unity.cloud.gltfast'...
remote: Enumerating objects: 12555, done.
remote: Counting objects: 100% (4454/4454), done.
remote: Compressing objects: 100% (493/493), done.
remote: Total 12555 (delta 4085), reused 4017 (delta 3961), pack-reused 8101
Receiving objects: 100% (12555/12555), 3.44 MiB | 15.03 MiB/s, done.
Resolving deltas: 100% (10216/10216), done.
Downloading Documentation~/Images/Unity-glTF-workflows.png (59 KB)
Error downloading object: Documentation~/Images/Unity-glTF-workflows.png (aa50e39): Smudge error: Error downloading Documentation~/Images/Unity-glTF-workflows.png (aa50e3980f8e9a99e53b8347cdde7e293fe37ffb5e1469640379d802ef304541): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to '[...]\com.unity.cloud.gltfast\.git\lfs\logs\20240202T140416.0968063.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Documentation~/Images/Unity-glTF-workflows.png: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Files**
none

**To Reproduce**
1. Go to attempt to clone the project on LFS-enabled git version 2.37.2.windows.2
2. See error

**Expected behavior**
Project should clone without error.

**Screenshots**

**Desktop (please complete the following information):**
 - glTFast version - repository
 - Unity Editor version [e.g. 2021.2.1f1] - N/A
 - Render Pipeline and version [e.g. Universal Render Pipeline 12.0] - N/A
 - Platform: [e.g. Editor, Windows Player, iOS] - N/A

**Additional context**
none

**Comment by mikeskydev** [comment]
Can reproduce on git 2.43.0.windows.1

**Comment by jbienzss** [comment]
I originally thought this was something wrong with the repo too, but I had forked it to my own account and it turned out that my account was actually over-allocated on LFS storage after forking it. So I just wanted to ask if you've verified you actually have plenty of free LFS storage? 

https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/viewing-your-git-large-file-storage-usage

It's possible you may have already verified this, and if so you're experiencing something different than I did. After I freed up some LFS space on my account I was in fact able to clone it just fine tonight. I too am running git version **2.43.0.windows.1**.

**Comment by jbienzss** [comment]
I just realized it's possible that the **Unity-Technologies** account may be out of LFS storage. If that is the case, you may be able to fork it to your own account and clone from there as I did. That is of course recommended if you were planning to submit a pull request back anyway.

**Comment by atteneder** [comment]
Sorry for the inconvenience. 

It just worked here, so I assume that the *Unity-Technologies* org leveled up the LFS quota. Please re-open if you experience it again.

Thanks
